services:
  helloworld:
    container_name: helloworld
    image: nginx
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`helloworld.${DOMAIN}`)"
      - "traefik.http.services.app.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
